#!/usr/bin/env pythonNone
# -*- coding: utf-8 -*-
#
# Copyright (c) 2018, German Aerospace Center (DLR)
#
# This file is part of the development version of FRASER.
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Authors:
# - 2018, Annika Ofenloch (DLR RY-AVS)

---
  # -------------------------------------------------------------------
  # Execute models local or remote
  # -------------------------------------------------------------------
- name: Run configuration server on the host
  command: "~/tmp_simulation/models/configuration_server/build/bin/configuration_server --config-file ~/tmp_simulation/hosts_config.xml"
  async: 1000
  poll: 0
  changed_when: False
  
- name: Run models on the hosts
  command: "~/tmp_simulation/models/{{ item }}/build/bin/{{ item }}"
  async: 1000
  poll: 0
  loop: "{{ hostvars[inventory_hostname]['models'] }}"
  when:
    - item != "simulation_model"
    - item != "configuration_server"
  changed_when: False
  
- name: Run simulation model on the host
  command: "~/tmp_simulation/models/simulation_model/build/bin/simulation_model --load-config ~/tmp_simulation/configurations/{{ config_path }}/"
  register: sim_out
  changed_when: False

- debug: var="sim_out.stdout_lines"
  when: sim_out.stdout_lines is defined
  # -------------------------------------------------------------------