# Copyright (c) 2015, German Aerospace Center (DLR)
# All Rights Reserved.

PROG= model_2
SRCS= main.cpp Model_2.cpp ../../fraser/src/communication/Subscriber.cpp ../../fraser/src/communication/Publisher.cpp \
../../fraser/src/communication/Dealer.cpp
BINDIR = build/bin
OBJDIR = build/obj

include ../../makefile.default.mk