# Copyright (c) 2017, German Aerospace Center (DLR)
#
# This file is part of the development version of FRASER.
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Authors:
# - 2018, Annika Ofenloch (DLR RY-AVS)

PROG = processing_element_2
SRCS= main.cpp ../../resources/src/ProcessingElement.cpp ../../resources/src/packet_generator.cpp ../../resources/src/packet_sink.cpp ../../resources/src/flit_utils.cpp ../../fraser/src/communication/Subscriber.cpp ../../fraser/src/communication/Publisher.cpp \
../../fraser/src/communication/Dealer.cpp
BINDIR = build/bin
OBJDIR = build/obj

include ../../makefile.default.mk