
PROG = eventQueue
SRCS= main.cpp Queue.cpp ../../fraser/src/communication/Subscriber.cpp ../../fraser/src/communication/Publisher.cpp \
../../fraser/src/communication/Dealer.cpp ../../fraser/src/scheduler/Scheduler.cpp
BINDIR = ../../bin
OBJDIR = ../../obj

include ../../makefile.default.mk