
PROG = event_queue_1
SRCS= main.cpp Queue.cpp ../../fraser/src/communication/Subscriber.cpp ../../fraser/src/communication/Publisher.cpp \
../../fraser/src/communication/Dealer.cpp ../../fraser/src/scheduler/Scheduler.cpp
BINDIR = build/bin
OBJDIR = build/obj

include ../../makefile.default.mk