# Copyright (c) 2017, German Aerospace Center (DLR)
#
# This file is part of the development version of FRASER.
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Authors:
# - 2017, Annika Ofenloch (DLR RY-AVS)

PROG = event_queue_1
SRCS := $(wildcard *.cpp) \
        $(wildcard ../../fraser/src/scheduler/*.cpp) \
        $(wildcard ../../fraser/src/communication/*.cpp)
        
BINDIR = build/bin
OBJDIR = build/obj

include ../../makefile.default.mk