#!/usr/bin/env pythonNone
# -*- coding: utf-8 -*-
#
# Copyright (c) 2018, German Aerospace Center (DLR)
#
# This file is part of the development version of FRASER.
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Authors:
# - 2018, Annika Ofenloch (DLR RY-AVS)

---
  # -------------------------------------------------------------------
  # Execute models locally to create default configuration files
  # -------------------------------------------------------------------
- name: Check if folder for configuration files exists
  file: path="../configurations/{{ config }}" state=directory

- name: Run configuration server locally
  shell: "../models/configuration_server/build/bin/configuration_server --config-file {{ hosts_config_filepath }}"
  async: 1000
  poll: 0
  changed_when: False
  
- name: Run models locally
  shell: "../models/{{ item }}/build/bin/{{ item }}"
  async: 1000
  poll: 0
  loop: "{{ models }}"
  when:
    - item != "simulation_model"
    - item != "configuration_server"
  changed_when: False
  
- name: Run simulation model locally
  shell: "../models/simulation_model/build/bin/simulation_model --create-config-files ../configurations/{{ config }}/"
  register: sim_output
  changed_when: False

- debug: var=sim_output.stdout_lines
  when: sim_output.stdout_lines is defined
  # -------------------------------------------------------------------