
PROG = simulation_model
SRCS= main.cpp SimulationModel.cpp ../../fraser/src/communication/Subscriber.cpp ../../fraser/src/communication/Publisher.cpp \
../../fraser/src/communication/Dealer.cpp
BINDIR = build/bin
OBJDIR = build/obj

include ../../makefile.default.mk