
PROG = simulationModel
SRCS= main.cpp SimulationModel.cpp ../../fraser/src/communication/Subscriber.cpp ../../fraser/src/communication/Publisher.cpp \
../../fraser/src/communication/Dealer.cpp
BINDIR = ../../bin
OBJDIR = ../../obj

include ../../makefile.default.mk